---
title: "Revision plan"
output: html_notebook
editor_options:
  chunk_output_type: inline
---


# TADs

I will send you locations of the ‘isolated’ peaks and you will visually compare with the U2OS TDAs – if they look a good fit, you will do a statistical analysis of the fit and we prepare another figure for the paper; otherwise we simply tell reviewers we had a look and they didn’t seem to fit.

File: ``r F_PEAKS_FOR_TADS``

Here is an Excel file for the possible position of TADS, using isolated peaks. My estimate for the peak start and peak end positions in Mbp are in the last two columns (F and G) and the chromosome is given in the first column (A). You can ignore the other columns which are there to give a clear way for me to track back to how I derived the positions.
 
 
# Figure 7 – peak width increase

I will send you a text file containing all the ‘isolated’ peaks at the 4 different time points. You will think of tests that a) they grow over the time course and b) whether the growth of the two later timepoints is consistent with a fork rate of approximately 1–2 kb/min.

File: ``r F_PEAK_GROWTH``

Here is the data I used on isolated peak growth. Peak size for the 4 timepoints was estimated using i) wavelet analysis (columns D to G); and ii) Gaussian curve fitting (columns H to K). You can see that there isn’t always both Gaussian and wavelet data for each peak, as I didn’t always get a fitted curve that met the required criteria for each time point, so these columns are blank (I eyeballed why this was happening, and it usually occurred where replication from a new or adjacent peak impinged on a peak that was ‘isolated’ in the first time point).


# Figure 9 – valley filling

I will send you a text file containing valley means and valley minima for the 4 different time points. You will think of a test to show that the valley signal is increasing over the time course.

File: ``r F_VALEY_FILLING``

Here is the data for valley filling. The file shows the chromosome and the valley region start and end in Mbp. Then, for each of the four time points (10-40, 40-70, 70-100 and 100-130 mins) there is a figure for the mean valley signal and the minimum valley signal.
 
# Figure 10 – peak activation order

I will send you a text file with my ‘adjacent height similarity’ metric for the 4 different timepoints. You will think of a test to show that these are all significantly positive.

File: ``r F_ADJACENT_HEIGHT_SIMILARITY``

Here is an excel file containing the ‘adjacent height similarity’ metrics for the four different time courses (columns A to D). The exact calculation is described in the paper, but it essentially calculates the sum of all the height differences between adjacent peaks in each group, and then normalises the sum so that a score of 1 would be all peaks in perfect order, and zero gives what would be expected if those peaks were in random order (I suspect, but haven’t been able to prove mathematically, that a score of -1 would be if the peaks appeared in maximally dissimilar order). You will notice that each number is repeated several times: this is because it analyses adjacent height similarity in groups of N adjacent peaks, where N is a minimum of 3, and calculates a single score for each group; the score for each group is repeated N-1 times to account for the number of adjacencies in each group when the overall statistics are presented in Figure 10.